version: '3.8'

services:
  intel-ml-service:
    image: pmckelvy/intel-ml-service
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    environment:
      - API_TOKEN=${API_TOKEN}
    restart: unless-stopped
