/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0a0c99ad282e49f67d596b158babe406)
declare namespace Cloudflare {
	interface Env {
		DATABASE_URL: string;
		GEMINI_API_KEY: string;
		ML_SERVICE_URL: string;
		ML_SERVICE_API_TOKEN: string;
		API_TOKEN: string;
		SOURCE_SCRAPER: DurableObjectNamespace<import("./src/index").SourceScraperDO>;
		ARTICLES_BUCKET: R2Bucket;
		ARTICLE_PROCESSING_QUEUE: Queue;
		PROCESS_ARTICLES: Workflow;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "GEMINI_API_KEY" | "ML_SERVICE_URL" | "ML_SERVICE_API_TOKEN" | "API_TOKEN">> {}
}
