version: '3.8'

services:
  briefs:
    image: briefs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MERIDIAN_SECRET_KEY=${MERIDIAN_SECRET_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
