name: Build docker
on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: [linux, x64]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: apps/briefs
          file: apps/briefs/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.login-ecr.outputs.registry }}/pmckelvy/meridian:latest
